### ISSUE TITLE
${@ annotations process even when within an if

### ISSUE THREAD

**Issue by brianblasko** [DJCordhose/jmte#13]
I noticed that ${@abc} type annotation processors are processed even when they are within an ${if} that does not evaluate to true.   Is this intentional?

${if 'a' = 'b'}
${@myannotation}
${end}

**Comment by DJCordhose** [comment]
Since we are lacking a formal specification, I do not know if it should be like this. Is this behavior bcurrently an issue for you?

**Comment by brianblasko** [comment]
I have some custom annotation processors that I wanted to use conditionally.
I have for instance one that can add a value to the model, kind of like a local variable.
I wanted to use it to set a model value based on the value of another model variable which means I only want to invoke the processor if the "if" was true.
${if condition}
${@set myValue= 'some other value'}
${end}

**Comment by DJCordhose** [comment]
the way if is currently is implemented is to evaluate everything inside a
condition and skip its output only

https://github.com/DJCordhose/jmte/blob/67c25a204b0c9a209bdeb3a4692bba55c6c09a06/src/com/floreysoft/jmte/template/InterpretedTemplate.java#L222

There could be an alternative implementation, but right now this will not
work.

Apart from that your use case sounds a little bit fishy to me...

**Comment by mlaggner** [comment]
This should be fixed with the PR https://github.com/DJCordhose/jmte/pull/29 in the next release
