### ISSUE TITLE
Engine is not thread safe?

### ISSUE THREAD

**Issue by dominik-cnx** [DJCordhose/jmte#15]
Because of this comment here (and because all the public methods are synchronized)

 * <p>
 * This class is thread safe.
 * </p>
 * 
 * @see ErrorHandler
 * @see Tool
 * @see Renderer
 * @see NamedRenderer
 * @see ModelAdaptor
 * @see ProcessListener
 */
public final class Engine implements RendererRegistry {

I expected the Engine to be thread safe, but I think it is actually not, see patch attached. It contains a unit test showing the issue. Also contains a fix, there is possibly a better way to solve the issue though.

[Added_test_to_illustrate_that_the_Engine_is_no_thread_safe.patch.zip](https://github.com/DJCordhose/jmte/files/7559218/Added_test_to_illustrate_that_the_Engine_is_no_thread_safe.patch.zip)

**Comment by DJCordhose** [comment]
Happy to look into it later today, any chance you can provide this as a proper PR?

**Comment by dominik-cnx** [comment]
Hey, great. 

I'm a little bit hesitant to create a PR because I'm uncertain if there are more case to consider and also if it make sense conceptually to simply create new parser instances over and over again.

**Comment by DJCordhose** [comment]
Can you at least send the test as a plain file or a PR? I am not sure what the patch was made against...

**Comment by DJCordhose** [comment]
Or maybe explain what the issue is and where in plain words?

**Comment by dominik-cnx** [comment]
OK, I'll create a PR with a failing test and also explain, should be easy.

Btw. I pulled today from the current master branch so it should be possible to apply the patch.

**Comment by DJCordhose** [comment]
having the PR with the explanation would be of great help

**Comment by dominik-cnx** [comment]
Here you go: https://github.com/DJCordhose/jmte/pull/16

**Comment by DJCordhose** [comment]
Having had a closer look, the mini parser causing the issue is used all over the place and making lots of copies seems rather sub optimal. Making the mini parser thread safe by making calls synhronized seems to be the better open,.

**Comment by DJCordhose** [comment]
I now made all methods of mini parser synchronized and that seems to make the test pass.

**Comment by DJCordhose** [comment]
@gunnarmorling has generously provided a lock free alternative implementation which is already merged

 @https://github.com/DJCordhose/jmte/pull/17

**Comment by dominik-cnx** [comment]
Do you plan to release this fix soon?

**Comment by DJCordhose** [comment]
version 7.0.0 containing the fix has been published

https://oss.sonatype.org/content/repositories/comfloreysoft-1024/com/floreysoft/jmte/7.0.0/
