### ISSUE TITLE
Conditional Shortcut only works for Strings

### ISSUE THREAD

**Issue by mlaggner** [DJCordhose/jmte#19]
the conditional shortcuts `${address(unknown)}` will only work for Strings. The problematic piece of code is at https://github.com/DJCordhose/jmte/blob/master/src/com/floreysoft/jmte/token/StringToken.java#L131

```
	private Object resolveDefault(Object value) {
		if (value == null || value.equals("")) {
			if (this.defaultValue != null) {
				value = defaultValue;
			}
		}
		return value;
	}
```

If `value` is no String, an `equals` will not work here. IMHO a `value.toString().equals` would be the right way

@DJCordhose what do you think?

**Comment by DJCordhose** [comment]
+1
