### ISSUE TITLE
Template `${\}` causes infinite loop and OutOfMemoryError

### ISSUE THREAD

**Issue by kreiger** [DJCordhose/jmte#25]
`com.floreysoft.jmte.util.Util.scan` enters an infinite loop and allocates all memory if an expression has an escaped `}` but no actual end `}`.

```
new Engine().getTemplate("${\\}");   // throws OutOfMemoryError
```

Normally this isn't a problem since templates are usually static, but i'm working on a tool that allows users to edit and test a template while the tool dynamically updates the result, and this bug is an almost instant crash.

**Comment by kreiger** [comment]
https://github.com/DJCordhose/jmte/pull/26

**Comment by mlaggner** [comment]
Your PR has been merged and a new release will be published in the next days
