### ISSUE TITLE
Map with enums not easily accessible

### ISSUE THREAD

**Issue by mlaggner** [DJCordhose/jmte#4]
I've used JMTE for a while now and could solve every requirement I could imagine. Now (due to refactoring) I've stumbled across a problem which is not easily solve able.

I have several beans in my project, which (now) contains maps holding some information. The key of the map is an enum and this leads to an (almost) unsolveable problem: We can only access map entries via JMTE which have a key type of String (I think the source is in DefaultModelAdaptor.java:153). 

```java
public enum MyType {
  TYPE_A, TYPE_B;
}

public class MyBean {
  public Map<MyType, String> myMap = new HashMap<>();
}
```
```java
String output = engine.transform("${bean.type.TYPE_A}", model);
```

Since I've an enum as key, JMTE cannot know how to convert it to the desired type for a map lookup (understandable). So my next idea was to create a getter method for the map which does the conversion, but unfortunately JMTE only calls the first method with the property name (this leads to another problem, which I will discuss later) regardless of the amount of parameters in the method signature (DefaultModelAdaptor.java:195 and :208). But there is no chance to pass the enum name as a parameter to the getter method.

a complete example is in the following gist:
https://gist.github.com/mlaggner/856e71db93d4910b108b

My idea was to introduce a new parameter for the tokens [methodParam1, methodParam2, ...] to JMTE to enable method invocation with arguments (which could solve my initial issue).

---
last but not least the problem with the methods: since JMTE call the first found method with the right name, it invokes that (via reflection) regardless of the method signature. If you take my example and switch the position of the methods:
* public String getType()
* public String getType(String typeAsString)

you will get an exception (java.lang.IllegalArgumentException).

**Comment by DJCordhose** [comment]
I do not see a way for JMTE to properly guess the types of the keys of a Map. Even if we had that information with the Map it could still contain subtypes of its specific generic type. Consider a map containing Object as key type - it can contain all kinds of types as keys.

What might work is to add the fully qualified type to the JMTE expression. Maybe like

`${bean.type.<MyType>TYPE_A}`

If whatever MyType is has a valueOf-Method that can turn a String into that type this should work.

What do you think? If the idea is good, what about the syntax?

**Comment by DJCordhose** [comment]
As an alternative we might iterate through all the Entries in a Map, turn the key into a String and compare the two. Slow, but more flexible. Maybe hidden behind a flag in the DefaultModelAdaptor? Turned on by default?

**Comment by DJCordhose** [comment]
I have added this test

	@Test
	public void enumAsKey() throws Exception {
		String output = newEngine().transform(
				"${bean.mapEnumAsKey.TYPE_A}", DEFAULT_MODEL);
		assertEquals("A", output);
	}

which now works with the slow, simple and flexible fix described above. 

Would this solve your problem?

**Comment by mlaggner** [comment]
that proposal would indeed solve my problem (just tried it against my project).
Thanks!

should I open a new issue for the reflection problem described on my first post?

**Comment by DJCordhose** [comment]
- Enum-Problem: great, I will close the issue
- Getters with parameters: JMTE will only support standard getters

**Comment by mlaggner** [comment]
I respect that JMTE will only support standard getters, but the problem I saw while creating the example exists in the currently code.
I'll prepare a new issue asap

**Comment by DJCordhose** [comment]
My understanding of getters for JavaBeans is that there should be no parameters to getters, so the problem seems to be in your code and not in JMTE, or am I missing something?

**Comment by mlaggner** [comment]
yes, this might be right that my code is "faulty" - but it works with any other dynamic invocations like beans binding.

I suppose the only thing you have to change is to check the method extracted via reflection has zero parameters to prevent calling the wrong one.

DefaultModelAdaptor.java line 228

```java            
              for (Method method : declaredMethods) {
                if (Modifier.isPublic(method.getModifiers())
                        && (method.getName().equals("get" + suffix) || method
                        .getName().equals("is" + suffix)) && method.getParameterTypes().length == 0) {
                    value = method.invoke(o, (Object[]) null);
                    valueSet = true;
                    member = method;
                    break;

                }
            }
```

**Comment by DJCordhose** [comment]
That makes sense to me. I will add that check. Or do you want to provide a
pull request?
Am 11.09.2015 5:52 nachm. schrieb "Manuel Laggner" <notifications@github.com
