### ISSUE TITLE
Publish 3.3.0 version

### ISSUE THREAD

**Issue by plarsson** [DJCordhose/jmte#6]
Hi, can you publish the latest 3.3.0 version on maven official? I'm interested in the fix where model is available on the NamedRenderer.

Thanks for a great library!

**Comment by DJCordhose** [comment]
I would need someone to publish 4.0.0 to maven central.

**Comment by mlaggner** [comment]
I am not a maven specialist, but the guide in http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/ should help.
As far as I can read out there, only the JIRA account, which owns the groupId (com.floreysoft) can publish a release there..

**Comment by mlaggner** [comment]
release of 4.0.0 has been done to maven central
